name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Run client/server in parallel. 
# Code checkout is small so low overhead, 
# npm build is slow, so benefits from parallelism
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - name: Set up JDK 111
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Archive
        run: tar -zcf /tmp/actiontest.tar.gz .
      - name: Upload 
        uses: actions/upload-artifact@v2
        with:
          name: Egeria test
          path: /tmp/actiontest.tar.gz