name: Test docker build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Run client/server in parallel. 
# Code checkout is small so low overhead, 
# npm build is slow, so benefits from parallelism
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        #if: ${{ github.event_name == 'push' && github.repository == 'odpi/egeria-react-ui' }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          #push:  ${{ github.event_name == 'push' && github.repository == 'odpi/egeria-react-ui' }} 
          push: true
          tags: odpi/egeria-presentation-server:latest
          context: .
          file: ./Dockerfile
          #build-args: |
          #  arg1=value1
          #  arg2=value2
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
