# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
name: "Test"

on:
  push:
    branches: [main, release-*, feature-*]
  # Also allow for manual invocation for testing
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Merge"
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container registry (Quay.io)
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # QEMU is needed for ARM64 build for egeria-configure
      # egeria-configure needs to install utilities
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set Release version env variables
        run: |
          echo "VERSION=$(./gradlew properties --no-daemon --console=plain -q | grep '^version:' | awk '{printf $2}')" >> $GITHUB_ENV
          echo "EGERIA_BASE_IMAGE=\"docker.io/odpi/egeria:$(./gradlew dependencies | grep org.odpi.egeria:open-connector-framework | awk -F':' '{print $3}' | awk -F' ' '{print $1}' | uniq| head -1)\"" >> $GITHUB_ENV
      - name: Build and push to docker.io and docker.io (tag latest only for main!)
        if: ${{ github.ref == 'refs/heads/main'}}
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: planetf1/testcontainer:${{ env.VERSION }}, planetf1/testcontainer:latest, docker.io/planetf1/testcontainer:${{ env.VERSION }}, docker.io/planetf1/testcontainer:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            EGERIA_BASE_IMAGE=${{ env.EGERIA_BASE_IMAGE }}
            VERSION=${{ env.VERSION }}

